### ISSUE TITLE
Geospatial Entity Resolution

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#15]
We need a way to quickly and efficiently map all geospatial information to GADM. For example, if the user provides ISO2 country codes (e.g. `AF`) we need to resolve this to the GADM country name (e.g. `Afghanistan`).

Additionally, if we receive data that has misspellings or non-standard ways of describing the country, we need to map this back to GADM.

We may potentially leverage ISI's wikifier and use the wikidata place identification to crosswalk back to GADM. 

```
curl -XPOST -F file=@fsi-2012.csv "https://dsbox02.isi.edu:8888/wikifier/wikify?k=3&columns=Country"
```

**Comment by GoogleSheets** [comment]
@brandomr So, I've spent some time looking at the options here, and talked with Kyle about how he implements `fuzzywuzzy` in geotime_classifier. There is also a `pycountry` package that does this in theory. `Fuzzywuzzy` will work only as well as the country dictionary we provide. I think the isi endpoint yields the best results (btw, they have another rest api at [https://dsbox02.isi.edu:9000/apidocs](https://dsbox02.isi.edu:9000/apidocs) ) but it does take some time to get a response from the api. Per Kyle's suggestion, we could match the easy ones against `pycountry` names and the 2- and 3-char abbreviations, and then ping the isi rest api for the ones that do not match easily.

**Comment by GoogleSheets** [comment]
[wikifier_test2.csv.txt](https://github.com/jataware/mixmasta/files/6594167/wikifier_test2.csv.txt)

rename to wikifier_test2.csv or modify the following command from the directory containing the test file:

`curl -X POST -F file=@wikifier_test2.csv "https://dsbox02.isi.edu:8888/wikifier/wikify?columns=Country" >> wikifier_test2_response.txt`

**Comment by brandomr** [comment]
@GoogleSheets have you tried this with more obscure admin 1, 2 and 3 yet? I’m curious how it performs and how quickly. I can create a test dataset if helpful.

Also, we’ll still need some way to crosswalk from whatever place names the ISI wikifier uses and GADM.
