### ISSUE TITLE
Add support for multi-band geotiff

### ISSUE THREAD

**Issue by GoogleSheets** [jataware/mixmasta#28]
### Add support for multi-band geotiff

- Each band will represent either a different time, a different feature, or a qualifier on the feature
- Time ex:  band 1 = 2015, band 2 = 2016, band 3 = 2017 etc
- Feature ex: band 1 = infant mortality rate, band 2 = avg life expectancy, band 3 = income level, etc
- Qualifier ex: band 1 = maize, band 2 = teff, band 3 = wheat, etc

### Questions
- Can each band be of a different type ex. band 1 = year, band 2 = income level, band 3 = wheat?

### Example File (4 bands)

Rename the following as a .tif file: [november_tests_atlasai_assetwealth_allyears_2km.renameAsTif.txt](https://github.com/jataware/mixmasta/files/6779009/november_tests_atlasai_assetwealth_allyears_2km.renameAsTif.txt)

### Example File loaded into dataframe (each band named somewhere + band#)

```
longitude  latitude  somewhere1  somewhere2  somewhere3  somewhere4
350.5      13.5           2           2           1           1
351.5      13.5           2           2           1           1
352.5      13.5           2           2           1           1
353.5      13.5           2           2           1           1
354.5      13.5           2           2           1           1
355.5      13.5           2           2           1           1
377.5      13.5           2           2           1           1
...
```

### Current example schema meta section for geotiff
```
"meta":
    {
        "ftype": "geotiff",
        "date": "",
        "feature_name": "somewhere",
        "band"1,
        "null_val": 0,	
    }
```

### Proposed schema changes to support multi-band geotiff
```
"meta":
{
	"ftype": "geotiff",
	"date": "",
	"feature_name": "somewhere",
	"band": 0,
	"null_val": 0,	
	"bands":[
		{ "band": 1, "feature_name": "pop" },
		{ "band": 2, "feature_name": "date" },
		{ "band": 3, "feature_name": "race" }
	]
}
```
`"name"` will give MixMasta the ability to identify the SpaceTag column description, e.g. band 1 above would refer to the following section within the schema:
```
"feature":
    [
        {
            "name": "pop",
            "display_name": "Pop",
            "description": "feat",
            "type": "feature",
            "feature_type": "int",
            "units": "asdcasd",
            "units_description": "asdcas"
        },
```

Added @BecketTrotter and @brandomr to discuss.

**Comment by GoogleSheets** [comment]
`flood_monthly.tif` (11MB so not uploaded here) is 50 rows x 222 columns, which suggests each band is a month and the data is some quantitative flooding measurement. This would change the proposed format above: each band would somehow need a date assigned to it.

**Comment by brandomr** [comment]
@GoogleSheets I think to your question:

> Can each band be of a different type ex. band 1 = year, band 2 = income level, band 3 = wheat?

I don't think that a modeler would mix temporal and categorical information across bands. If they did, well...what a poor design decision on their end! Let's ignore that edge case for now.

There are two use cases we have to support

1. The initial conversion of GeoTiff to table for annotation in Spacetag. Here the GeoTIFF is converted into a very basic table/dataframe 
2. The transformation of a GeoTiff into a CauseMos compliant format.

For #1 the key to keep in mind is that what @BecketTrotter does [where he calls `mix.raster2df`](https://github.com/jataware/spacetag/blob/main/byod/conversions.py#L68-L83) will have to change. That `raster2df` function within Mixmasta will need to accept some new information about what the bands mean. Keep in mind, some bands may be worthless and should be ignored. 

The more and more I consider it, I cannot think of a scenario where we would do anything but add one column for whatever is represented in the band and then stack the data.

Imagine a single band geotiff where the band has no meaning. Let's say that it has 2 pixels, where the value represents rainfall:

| Lat     | Lon    | Rainfall |
|---------|--------|----------|
| 11.2233 | -5.222 | 0.5      
| 11.3455 | -6.234 | 0.8      

Now let's imagine this has two bands, band 1 = year 2020 and band 2 = year 2021. The tabular representation of this data should look like:

| Lat     | Lon    | Rainfall | Year |
|---------|--------|----------|------|
| 11.2233 | -5.222 | 0.5      | 2020 |
| 11.3455 | -6.234 | 0.8      | 2020 |
| 11.2233 | -5.222 | 0.5      | 2021 |
| 11.3455 | -6.234 | 0.8      | 2021 |

What if bands represent something else, such as farm type (band 1 = rainfed, band 2 = irrigated)? It would basically look like:

| Lat     | Lon    | Rainfall | Farm Type |
|---------|--------|----------|------|
| 11.2233 | -5.222 | 0.5      | rainfed |
| 11.3455 | -6.234 | 0.8      | rainfed |
| 11.2233 | -5.222 | 0.5      | irrigated |
| 11.3455 | -6.234 | 0.8      | irrigated |

Now we actually do ask the user for time as well so there is a case where the entire file represents some time, let's say `February, 2021`. In this case bands cannot represent time but must represent some kind of categorical information. Could the user tell us that they represent time? Sure, but would be user error; we'd just treat the time as a category. But generally if they said the date is `February, 2021` and bands represent Farm Type then we'd have:

| Lat     | Lon    | Rainfall | Date           | Farm Type |
|---------|--------|----------|----------------|-----------|
| 11.2233 | -5.222 | 0.5      | February, 2021 | rainfed   |
| 11.3455 | -6.234 | 0.8      | February, 2021 | rainfed   |
| 11.2233 | -5.222 | 0.5      | February, 2021 | irrigated |
| 11.3455 | -6.234 | 0.8      | February, 2021 | irrigated |

> **The key here** seems to be that if we have a 2 pixel raster (GeoTIFF) with two farms, one at `11.2233, -5.222` and the other at `11.3455, -6.234` we'd need to repeat their lat/lon for each band that is of interest to the user.

@GoogleSheets let me know if this makes sense to you; definitely can discuss tomorrow if helpful.

**Comment by brandomr** [comment]
For the mixmasta [`raster2df`](https://github.com/jataware/mixmasta/blob/master/mixmasta/mixmasta.py#L1044) function I think asking for a band dictionary like you suggest above would work well and could simplify to:

```
{1: "rainfed"},
{2: "irrigated"}
```
or
```
{1: 2020},
{2: 2021}
```
you'd also need to ask for what "band represents" so maybe an argument called `band_name` where in 1) above it would be `farm type` and 2) would be `year`.

I'm less clear on how this should be handled from the Spacetag annotation mapper; I think that whatever value is given to `band_name` has to show up as a `name` in an `output` or `qualifier`

**Comment by GoogleSheets** [comment]
### Schema modification and examples

**Example of proposed schema change (for a geotiff with 4 bands):**
```
"meta":
    {
        "ftype": "geotiff",
        "date": "12/29/2004",
        "feature_name": "asset wealth",		
        "band": 0,
        "null_val": 0,	
        "band_name": "year",
        "bands":{
	        "1": 2018,
	        "2": 2019,
	        "3": 2020,
	        "4": 2021		
        }
    }
```
**Additions to current schema "meta" section:**
```
"band_name": str
"bands": dict(str, object)
```

**Notes regarding `november_tests_atlasai_assetwealth_allyears_2km.tif`:**
872 x 677 pixels
4 bands
raster2df() time: 4.05 seconds

**Dataframe (sorted) returned by raster2df and example schema above (409047 rows, 4 columns):**
```
       longitude  latitude  asset wealth  year        date
75410        0.5     410.5             1  2018  12/29/2004
75459        0.5     410.5             1  2019  12/29/2004
51932        0.5     410.5             1  2020  12/29/2004
33755        0.5     410.5             1  2021  12/29/2004
75742        0.5     411.5             1  2018  12/29/2004
75789        0.5     411.5             1  2019  12/29/2004
52184        0.5     411.5             1  2020  12/29/2004
33959        0.5     411.5             1  2021  12/29/2004
76061        0.5     412.5             1  2018  12/29/2004
76104        0.5     412.5             1  2019  12/29/2004
52422        0.5     412.5             1  2020  12/29/2004
```

### Comments

1. "band" is retained for backwards compatibility. If "band" > 0 then only that band will be processed; else, only the specified bands in "bands" will be processed.
2. If "date" is provided that value will be used for each row in column "date".
3. The value in `"bands"` e.g. 2021, "corn", "1/1/1980" are added to the return `raster2df()` dataframe as a `str`.
4. Timing: **`raster2df()`**: ~4.5 sec; **`process()`**: ~245 sec
5. Latitude values range from 0.5 to 859.5, longitude from to ~410 to ~600. These are invalid values and need to be addressed. It could be the source file.
