### ISSUE TITLE
Causemosify multiple files at once

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#30]
## Overview

We need a way to `causemosify` multiple files at once. Many models produce more than one output file, sometimes in different formats. Each output file should therefore be expected to have it's own mapper file. However, the `causemosification` should occur at equivalent `geo` levels for each file (basically, always `admin3` for World Modelers).

## Technical implementation

We need either a new function for [`causemosify`](https://github.com/jataware/mixmasta/blob/dev/mixmasta/cli.py#L19-L41) or an enhancement to this existing function which enables a user to send multiple input files and mapper files and produce multiple outputs.

This should retain the ability to have wildcards in the `input_file` name.

### Options

We could have a parameter called `inputs` which is an array like:

```
[
   {
      "input_file":"file_1_*.csv",
      "mapper":"mapper_1.json",
      "output_file":"output_1"
   },
   {
      "input_file":"file_2.csv",
      "mapper":"mapper_2.json",
      "output_file":"output_2"
   }
]
```

Are there more elegant/easier options to implement?

**Comment by GoogleSheets** [comment]
This seems like the simplest approach. Adding this amplifies the size of the data returned at one time, but that is probably already managed. 

I'll create a new feature branch off of dev and start on it.

**Comment by brandomr** [comment]
Sounds good--will you overwrite the `causemosify` function or add a new one?

**Comment by GoogleSheets** [comment]
I think I'll add a new one with the single parameter: `cli.causemosify_multi(inputs)`
