### ISSUE TITLE
Geocoding and Timestamp Efficiencies

### ISSUE THREAD

**Issue by GoogleSheets** [jataware/mixmasta#36]
### Description

`geocode()` calls `geopandas.GeoDataFrame` on the entire dataset: 

```
df["geometry"] = df.apply(lambda row: Point(row[x], row[y]), axis=1)
gdf = gpd.GeoDataFrame(df)
```

This is inefficient for most datasets that have repeated locations, but for multi-band geotiffs with many bands this is highly efficient. **floody_montly.tif** for example has 220 bands of repeated lat/lng values.

### Potential Solutions

Get the unique set of lat/lng and geopandas.GeoDataFrame() into a temporary dataframe to use for a `lookup` or `join`.

**Comment by brandomr** [comment]
@GoogleSheets let's also consider generic files; can we round (e.g. to 2 decimal places or even 1 decimal) lat/lon, dedupe them and geocode only those.

For example, a lat/lon of `11.23124, 80.24323` becomes `11.2` and `80.2`. Ideally this yields far fewer points to geocode.

> Think a bit about whether to round to 1 or 2 decimal places. See [decimal precision](http://wiki.gis.com/wiki/index.php/Decimal_degrees) for more.

Same for timestamps--can we dedupe and only convert what is necessary?
