### ISSUE TITLE
Possibility that admin1 is entity-resolved to admin2?

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#38]
Reported by Brad Goodman. See https://darpa-world-modelers.slack.com/archives/C023E7NU3GS/p1626713091231900

**Comment by GoogleSheets** [comment]
The short answer is that the dataset is using Coast, Central, Eastern, North Eastern, Nyanza, Rift Valley, Western in `Admin1`, but according to **GADM**, `Admin1` for Kenya should be: 

'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu', 'Garissa', 'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho',
       'Kiambu', 'Kilifi', 'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu', 'Machakos', 'Makueni', 'Mandera',
       'Marsabit', 'Meru', 'Migori', 'Mombasa', "Murang'a", 'Nairobi',
       'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua', 'Nyeri',
       'Samburu', 'Siaya', 'Taita Taveta', 'Tana River', 'Tharaka-Nithi',
       'Trans Nzoia', 'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir',
       'West Pokot'.

Brad says those look like `Admin2`.

**Comment by brandomr** [comment]
[GADM_kenya.csv](https://github.com/jataware/mixmasta/files/6843775/GADM_kenya.csv)

My double check on the GADM file showed these. Very different from wikipedia/what Brad posted. Let's leave this issue open and see what Brad thinks best to resolve it.

**Comment by GoogleSheets** [comment]
@brandomr That's what I saw both in Kenya-specific files downloaded today, and the complete GADM mega-monster downloaded in June.

**Comment by brandomr** [comment]
Cool I just used some cached version I had handy. It will be annoying if GADM is just plain wrong...
