### ISSUE TITLE
Mixmasta normalizer unknown bug

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#39]
## Overview

Reported by MITRE, verified by @brandomr. Recreate by going to https://data.dojo-test.com/overview/9363942e-bdc2-40cb-9026-fca29bf581fa. Edit `MainCause` and make it qualify one of the other features (e.g. `Displaced`). Submit.

## Traceback

```
norm.to_parquet(f"{output_file}.parquet.gzip", compression="gzip")
```

fails with (PyArrow error):

```
("Expected bytes, got a 'int' object", 'Conversion failed for column MainCause with type object')
```

## Associated Files for Testing
[raw_excel.xlsx](https://github.com/jataware/mixmasta/files/6851780/raw_excel.xlsx)
[sent_to_mixmasta.json.txt](https://github.com/jataware/mixmasta/files/6851789/sent_to_mixmasta.json.txt)

**Comment by brandomr** [comment]
@GoogleSheets when I tried running this locally with a fresh mixmasta Docker build the error was perhaps more telling....

```
pyarrow.lib.ArrowInvalid: ("Could not convert ' Heavy Rain and Tropical Storm Soul' with type str: tried to convert to int", 'Conversion failed for column MainCause with type category')
```

**Comment by brandomr** [comment]
It looks like in the Excel there are some blanks in that column. I wonder if they are converted to `NaN` by Pandas or something and then that causes the parquet file writing to puke

**Comment by GoogleSheets** [comment]
> It looks like in the Excel there are some blanks in that column. I wonder if they are converted to `NaN` by Pandas or something and then that causes the parquet file writing to puke

@brandomr We added this to intentionally convert the blanks and nulls to NaN for consistency:
```
# Normalizer will add NaN for missing values, e.g. when appending
# dataframes with different columns. GADM will return None when geocoding
# but not finding the entity (e.g. admin3 for United States).
# Replace None with NaN for consistency.
norm.fillna(value=np.nan, inplace=True)
```

**Comment by brandomr** [comment]
Ah gotcha. 🤷‍♂️ ok no clue what it might be then. Maybe that leading white space but that seems silly
