### ISSUE TITLE
If timestamp is a column, but not primary

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#65]
https://github.com/jataware/mixmasta/blob/master/mixmasta/mixmasta.py#L780 `staple_col_name` in this case won't be defined and there will be an error.

**Comment by GoogleSheets** [comment]
@brandomr Do you want a hotfix off master or feature off dev?

**Comment by brandomr** [comment]
@GoogleSheets I'd just roll in a fix into your admin1+ reverse geocoding PR when that's ready.
